### ISSUE TITLE
After update angular 10 I have got a compilation errors. 

### ISSUE THREAD

**Issue by harleenarora** [isaacplmann/ngx-tour#219] opened 2020-07-15 12:06 UTC
Error::
`Error: Failed to compile entry-point ngx-tour-ng-bootstrap (es2015 as esm2015) due to compilation errors:
node_modules/ngx-tour-ng-bootstrap/fesm2015/ngx-tour-ng-bootstrap.js:248:26 - error NG1010: Value at position 1 in the NgModule.imports of TourNgBootstrapModule is not a reference: [object Object]

248                 imports: [CommonModule, NgbPopoverModule.forRoot()],`

Please solved this issue.

**Comment by fergardi** [comment] 2020-07-22 09:25
Duplicate from #215

**Comment by abdulbadisabir** [comment] 2020-10-30 05:21
I have the exact same error, any news?

**Comment by alvaro-octal** [comment] 2020-11-05 10:13
This is now fixed, but we need a release @isaacplmann

**Comment by notman** [comment] 2021-01-25 19:14
Any chance this release will be soon? We are at a stopping point, in our current upgrade to Angular 11

**Closed** 2021-03-31 09:47 UTC

**Comment by hakimio** [comment] 2021-04-06 12:20
@notman 
Bad news: Isaac Mann stopped maintaining this project some time ago and I don't have access to publish new npm packages.
Good news: I have created [a fork](https://github.com/hakimio/ngx-ui-tour) and I have published a new version under a new name: `ngx-ui-tour`. It's compatible with Angular 11. Test it out and let me know if it works as intended.
