### ISSUE TITLE
the project is loading fine but no tour step has been displayed in angular-cli template

### ISSUE THREAD

**Issue by mohamedabdeen** [isaacplmann/ngx-tour#10] opened 2017-03-17 15:46 UTC
i followed the steps as the demo and install everything and project is loading fine but no steps have been displayed

1. use  angular-cli project template 
2. install scroll-into-view (https://github.com/stipsan/scroll-into-view-if-needed)
3. install angular-hotkeys (https://www.npmjs.com/package/angular2-hotkeys)
4. install ng2-tour 

and then follow all steps as ur step, i attached package json file 
[package.txt](https://github.com/isaacplmann/ng2-tour/files/851086/package.txt)

in the app.component.ts , in constructor the following code 

`      this._tourService.initialize([{
            anchorId: 'anchor.KPISubmission',
            content: 'welcome to Some content',
            placement : 'below',
            route:'dashboard',
            title: 'First',
      }]);
      this._tourService.start();`

Pls advise

**Comment by isaacplmann** [comment] 2017-03-17 15:51
Did you include the bootstrap css?

```html
<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
```

I should add that step to the documentation.

**Comment by mabdeen84** [comment] 2017-03-17 15:57
Yes, bootstrap (v3.3.7) is already included in my project in index.html file

**Comment by isaacplmann** [comment] 2017-07-19 18:53
Closing as can't reproduce

**Closed by isaacplmann** 2017-07-19 18:53 UTC
