### ISSUE TITLE
Need some Help

### ISSUE THREAD

**Issue by wafimardini** [isaacplmann/ngx-tour#8] opened 2017-03-13 15:21 UTC
Hi Isacc
i did the implementation.However after clicking the next button to go to next tour throwes error and exit the program any suggestions?

**Comment by isaacplmann** [comment] 2017-03-13 16:04
I'm on vacation until Thursday.  I'll need the error message to help you
when I get back.

**Comment by wafimardini** [comment] 2017-03-13 17:12
Thank you enjoy your vacation
here is screenshot i get object no errors when i click next does't continue and log me out of my cms
<img width="1895" alt="screen shot 2017-03-13 at 1 10 14 pm" src="https://cloud.githubusercontent.com/assets/7050312/23866282/b610ebfa-07ee-11e7-8f7a-e5201ab3f192.png">

**Comment by isaacplmann** [comment] 2017-03-16 13:18
That looks like its a css problem.  The `Object` in the console is just a debugging line I forgot to remove from the code.  Can you check and see if you can use a normal [NgbPopover](https://ng-bootstrap.github.io/#/components/popover) from the [ng-bootstrap](https://ng-bootstrap.github.io/#/getting-started) library in your app?  I use that library to handle all the positioning and popup logic.

**Comment by mabdeen84** [comment] 2017-03-17 15:49
@wafimardini how you make it work for your project, i did all the steps in angular-cli template project and the project was loading fine without errors but no tour step has been displayed

**Comment by isaacplmann** [comment] 2017-07-19 18:54
Closing as can't reproduce

**Closed by isaacplmann** 2017-07-19 18:54 UTC
