### ISSUE TITLE
Uncaught TypeError: _ng_bootstrap_ng_bootstrap__WEBPACK_IMPORTED_MODULE_2__.NgbPopoverModule.forRoot is not a function

### ISSUE THREAD

**Issue by faceoffers28** [isaacplmann/ngx-tour#187] opened 2019-10-17 17:18 UTC
Simply adding the following to app.module.ts causes the Uncaught TypeError.

import { TourNgBootstrapModule } from 'ngx-tour-ng-bootstrap';

TourNgBootstrapModule.forRoot(),

Uncaught TypeError: _ng_bootstrap_ng_bootstrap__WEBPACK_IMPORTED_MODULE_2__.NgbPopoverModule.forRoot is not a function
    at Module../node_modules/ngx-tour-ng-bootstrap/fesm2015/ngx-tour-ng-bootstrap.js (ngx-tour-ng-bootstrap.js:182)
    at __webpack_require__ (bootstrap:79)
    at Module../src/app/app.module.ts (app.component.ts:10)
    at __webpack_require__ (bootstrap:79)
    at Module../src/main.ts (main.ts:1)
    at __webpack_require__ (bootstrap:79)
    at Object.0 (main.ts:12)
    at __webpack_require__ (bootstrap:79)
    at checkDeferredModules (bootstrap:45)
    at Array.webpackJsonpCallback [as push] (bootstrap:32)

I'm running the following versions.
Angular CLI = 8.1
TypeScript = 3.4.5
WebPack = 4.35.2

Any help is much appreciated. Thanks!

**Comment by herrKlein** [comment] 2019-12-17 13:29
I am running into the same error. , looks like if you remove .forRoot() it kinda works. But then there is still an error when clicking start twice or clicking next to the popup. Also reproducible in the demo page of ng-bootstrap implementation. Clicking twice throws this error: 

```main-es2015.83a5758b6d0fd81ebc2f.js:1 ERROR TypeError: Cannot read property 'step' of undefined```

But nice library btw

**Comment by karamjeetiron** [comment] 2020-01-24 10:48
I have same issue @faceoffers28 . Has you find any hack of this till now?

**Comment by faceoffers28** [comment] 2020-01-24 18:12
@karamjeetiron I did not figure it out and used another JS tool that works great in both my Angular and MVC apps.

**Comment by karamjeetiron** [comment] 2020-01-27 11:29
@isaacplmann Please help me to fix it.

**Comment by isaacplmann** [comment] 2020-02-19 19:54
Fixed in ngx-tour-ng-bootstrap@5.0.0

**Closed by isaacplmann** 2020-02-19 19:54 UTC

**Comment by schaefermichael** [comment] 2020-03-01 12:13
@isaacplmann Could you publish 5.0.0 on npm?

**Comment by h11a** [comment] 2020-11-17 11:01
Any plans on publishing it?
